### ISSUE TITLE
Create booking entry like ...

### ISSUE THREAD

**Issue by lg2de** [lg2de/SimpleAccounting#187]
It would be great to create a new booking entry based on an existing entry.

**Comment by mrzhdev** [comment]
Hi,

I have implemented this and you could find the code on:
https://github.com/mrzhdev/SimpleAccounting/commit/7ea4bfe771adef219ea337e589bc3b838ee890b2

++

Have nice weekend.

**Comment by lg2de** [comment]
Do you want to create a pull request?

**Comment by mrzhdev** [comment]
I was thinking that you would like to take a look before making a pull request.
Anyway, I will make the pull request.
